name: Quality

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test-backward.txt

    - name: Invoke Quality
      run: inv quality


